// packages/svelte/src/lib/components/code/CodeItem.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import styles from "@fefade-ui/core/styles/CodeItem.module.css"

	interface Props extends HTMLAttributes<HTMLPreElement> {
		lineNumber: number
	}

	let { class: className = "", lineNumber, children, ...rest }: Props = $props()
</script>

<pre
	{...rest}
	class={classMapUtil(className, [className, styles], styles.codeItem)}
	data-prefix={lineNumber}>
    <code class={styles.content}>{@render children?.()}</code>
</pre>

// packages/react/src/lib/components/code/CodeItem.tsx
import { classMapUtil } from "@fefade-ui/core/utils"
import { forwardRef, HTMLAttributes } from "react"
import styles from "@fefade-ui/core/styles/CodeItem.module.css"

interface Props extends HTMLAttributes<HTMLPreElement> {
	lineNumber: number
}

export default forwardRef<HTMLPreElement, Props>(
	({ className = "", lineNumber, children, ...rest }, ref) => {
		return (
			<pre
				{...rest}
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					styles.codeItem
				)}
				data-prefix={lineNumber}
			>
				<code className={styles.content}>{children}</code>
			</pre>
		)
	}
)
