// packages/svelte/src/lib/components/video/Video.svelte
<script lang="ts">
	import { videoAction } from "@fefade-ui/core/actions"
	import type { VideoType } from "@fefade-ui/core/types"
	import { videoUtil } from "@fefade-ui/core/utils"
	import type { HTMLVideoAttributes } from "svelte/elements"

	interface Props
		extends Omit<Omit<Omit<HTMLVideoAttributes, "src">, "color">, "type">,
			VideoType {}

	let { class: className = "", lazy, dataSrc, ...rest }: Props = $props()

	const { getVideoType } = videoUtil()

	let el: HTMLVideoElement
</script>

<video
	{...rest}
	use:videoAction={{ lazy }}
	bind:this={el}
	class={className}
	preload={lazy ? "none" : undefined}
	onmouseenter={() => {
		el.pause()
	}}
	onmouseleave={() => {
		el.play()
	}}
	data-src={dataSrc}
>
	<source type="video/{getVideoType(dataSrc).replace('.', '')}" />
</video>

// packages/react/src/lib/components/video/Video.tsx
import { useAction } from "@/utils"
import { videoAction } from "@fefade-ui/core/actions"
import type { HTMLAttrAnchor, VideoType } from "@fefade-ui/core/types"
import { videoUtil } from "@fefade-ui/core/utils"
import { forwardRef, ImgHTMLAttributes } from "react"

interface Props
	extends Omit<
			Omit<ImgHTMLAttributes<Omit<HTMLVideoElement, "src">>, "color">,
			"type"
		>,
		VideoType,
		HTMLAttrAnchor {}

export default forwardRef<HTMLVideoElement, Props>(
	({ className = "", lazy = false, dataSrc, ...rest }, _ref) => {
		const actionRef = useAction<
			HTMLVideoElement,
			Parameters<typeof videoAction>[1]
		>(videoAction, { lazy })

		const { getVideoType } = videoUtil()

		return (
			<video
				{...rest}
				ref={actionRef}
				className={className}
				preload={lazy ? "none" : undefined}
				onMouseEnter={() => {
					actionRef.current?.pause()
				}}
				onMouseLeave={() => {
					actionRef.current?.play()
				}}
				data-src={dataSrc}
			>
				<source type={`video/${getVideoType(dataSrc).replace(".", "")}`} />
			</video>
		)
	}
)
