// packages/docs/src/lib/components/AlertPreview.tsx
import { Constants } from "@fefade-ui/core"
import { Alert } from "@fefade-ui/react"

export default function () {
	return (
		<div>
			{Constants.statusColors.map((color) => (
				<div key={color}>
					<Alert color={color}>
						<div style={{ display: "flex", flexDirection: "column" }}>
							<strong>{color}</strong>
							<small>description</small>
						</div>
					</Alert>
				</div>
			))}
		</div>
	)
}

// packages/docs/src/lib/components/AlertPreview.svelte
<script lang="ts">
	import { Alert } from "@fefade-ui/svelte"
	import { Constants } from "@fefade-ui/core"
</script>

<br />

{#each Constants.statusColors as color (color)}
	<Alert {color}>
		<div style="display: flex; flex-direction: column;">
			<strong>{color}</strong>
			<small>description</small>
		</div>
	</Alert>
	<br />
{/each}
