// apps/docs/src/lib/components/BadgePreview.vue
<script setup lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { Badge } from "@fefade-ui/vue"

	const badgeVariants = ["outlined", "contained"] as const
</script>

<template>
	<div style="display: flex; flex-wrap: wrap; align-items: flex-end; gap: 1rem">
		<Badge
			v-for="color in Constants.statusColors"
			:key="color"
			:class="`bg-${color} text-on-${color}`"
			size="md"
		>
			{{ color }}
		</Badge>

		<Badge
			v-for="variant in badgeVariants"
			:key="variant"
			:variant="variant"
			size="md"
		>
			{{ variant }}
		</Badge>

		<Badge
			v-for="size in Constants.sizes"
			:key="size"
			:size="size"
			rounded-full
		>
			{{ size }}
		</Badge>
	</div>
</template>

// packages/docs/src/lib/components/BadgePreview.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { Badge } from "@fefade-ui/svelte"

	const badgeVariants = ["outlined", "contained"] as const
</script>

<div
	style="
    display: flex; 
    flex-wrap: wrap;
    align-items: flex-end;
    gap: 1rem;
    "
>
	{#each Constants.statusColors as color (color)}
		<Badge class="bg-{color} text-on-{color}" size="md">
			{color}
		</Badge>
	{/each}
	{#each badgeVariants as variant (variant)}
		<Badge {variant} size="md">
			{variant}
		</Badge>
	{/each}
	{#each Constants.sizes as size (size)}
		<Badge roundedFull {size}>
			{size}
		</Badge>
	{/each}
</div>
