// packages/docs/src/lib/components/BadgePreview.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { Badge } from "@fefade-ui/svelte"

	const badgeVariants = ["outlined", "contained"] as const
</script>

<div
	style="
    display: flex; 
    flex-wrap: wrap;
    align-items: flex-end;
    gap: 1rem;
    "
>
	{#each Constants.statusColors as color (color)}
		<Badge class="bg-{color} text-on-{color}" size="md">
			{color}
		</Badge>
	{/each}
	{#each badgeVariants as variant (variant)}
		<Badge {variant} size="md">
			{variant}
		</Badge>
	{/each}
	{#each Constants.sizes as size (size)}
		<Badge roundedFull {size}>
			{size}
		</Badge>
	{/each}
</div>

// packages/docs/src/lib/components/BadgePreview.tsx
import { Constants } from "@fefade-ui/core"
import { Badge } from "@fefade-ui/react"

export default function () {
	const badgeVariants = ["outlined", "contained"] as const

	return (
		<div
			style={{
				display: "flex",
				flexWrap: "wrap",
				alignItems: "flex-end",
				gap: "1rem"
			}}
		>
			{Constants.statusColors.map((color) => (
				<Badge
					key={`color-${color}`}
					className={`bg-${color} text-on-${color}`}
					size="md"
				>
					{color}
				</Badge>
			))}

			{badgeVariants.map((variant) => (
				<Badge key={`variant-${variant}`} variant={variant} size="md">
					{variant}
				</Badge>
			))}

			{Constants.sizes.map((size) => (
				<Badge key={`size-${size}`} size={size} roundedFull>
					{size}
				</Badge>
			))}
		</div>
	)
}
