// apps/docs/src/lib/components/SpinnerPreview.vue
<script setup lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { Spinner } from "@fefade-ui/vue"
</script>

<template>
	<div
		style="display: flex; flex-wrap: wrap; align-items: baseline; gap: 1.5rem"
	>
		<div
			v-for="color in Constants.statusColors"
			:key="`color-${color}`"
			style="display: flex; flex-direction: column; align-items: center"
		>
			<Spinner :class="`text-on-${color}`" size="md" />
			<span>{{ color }}</span>
		</div>

		<div
			v-for="size in Constants.sizes"
			:key="`size-${size}`"
			style="display: flex; flex-direction: column; align-items: center"
		>
			<Spinner :size="size" color="primary" />
			<span>{{ size }}</span>
		</div>
	</div>
</template>

// packages/docs/src/lib/components/SpinnerPreview.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { Spinner } from "@fefade-ui/svelte"
</script>

<div
	style="
	display: flex;
	flex-wrap: wrap;
	align-items: baseline;
	gap: 1.5rem;
	"
>
	{#each Constants.statusColors as color (color)}
		<div
			style="
			display: flex;
			flex-direction: column;
			align-items: center;
			"
		>
			<Spinner class="text-on-{color}" size="md" />
			<span>{color}</span>
		</div>
	{/each}

	{#each Constants.sizes as size (size)}
		<div
			style="
			display: flex;
			flex-direction: column;
			align-items: center;
			"
		>
			<Spinner {size} color="primary" />
			<span>{size}</span>
		</div>
	{/each}
</div>
