// packages/docs/src/lib/components/TextFieldPreview.tsx
import { Constants } from "@fefade-ui/core"
import { TextField } from "@fefade-ui/react"

export default function () {
	return (
		<div
			style={{
				maxWidth: "300px",
				margin: "0 auto"
			}}
		>
			{Constants.variants.map((variant, i) => {
				const size = Constants.sizes[i + 1]
				return (
					<div key={i}>
						<TextField
							label={`${variant} (${size})`}
							variant={variant}
							size={size}
						/>
						<br />
						<br />
					</div>
				)
			})}
		</div>
	)
}

// packages/docs/src/lib/components/TextFieldPreview.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { TextField } from "@fefade-ui/svelte"
</script>

<div style="max-width: 300px; margin: 0 auto;">
	{#each Constants.variants as variant, i (i)}
		{@const size = Constants.sizes[i + 1]}
		<TextField label={`${variant} (${size})`} {variant} {size} />
		<br />
		<br />
	{/each}
</div>
