// apps/docs/src/lib/components/ToastPreview.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { Button, toast } from "@fefade-ui/svelte"

	const positions = [
		"top-left",
		"bottom-left",
		"top-right",
		"bottom-right",
		"bottom-center",
		"top-center"
	] as const
</script>

<div style="display: flex; gap: 1rem; align-items: center; flex-wrap: wrap;">
	{#each Constants.statusColors as color (color)}
		<Button
			onclick={() => {
				toast({
					message: color,
					color
				})
			}}
			class={`bg-${color} text-on-${color}`}
		>
			{color}
		</Button>
	{/each}

	{#each positions as position (position)}
		<Button
			onclick={() => {
				toast({
					message: position,
					position
				})
			}}
		>
			{position}
		</Button>
	{/each}

	<Button
		onclick={() => {
			toast({
				message: "Duration: 50000",
				duration: 50000
			})
		}}
	>
		Duration: 50000
	</Button>

	<Button
		onclick={() => {
			toast({
				message: "closable",
				isClosable: true
			})
		}}
	>
		Closable
	</Button>

	<Button
		onclick={() => {
			toast({
				message: "with progress loader",
				withProgressLoader: true,
				duration: 15000
			})
		}}
	>
		With Progress Loader
	</Button>
</div>

// packages/docs/src/lib/components/ToastPreview.tsx
import { Constants } from "@fefade-ui/core"
import { Button, Toaster, useToast } from "@fefade-ui/react"

function ToastPreview() {
	const toast = useToast()

	const positions = [
		"top-left",
		"bottom-left",
		"top-right",
		"bottom-right",
		"bottom-center",
		"top-center"
	] as const

	return (
		<div
			style={{
				display: "flex",
				gap: "1rem",
				alignItems: "center",
				flexWrap: "wrap"
			}}
		>
			{Constants.statusColors.map((color) => (
				<Button
					key={color}
					onClick={() => {
						toast.add({
							message: color,
							color
						})
					}}
					className={`bg-${color} text-on-${color}`}
				>
					{color}
				</Button>
			))}

			{positions.map((position) => (
				<Button
					key={position}
					onClick={() => {
						toast.add({
							message: position,
							position
						})
					}}
				>
					{position}
				</Button>
			))}

			<Button
				onClick={() => {
					toast.add({
						message: "Duration: 50000",
						duration: 50000
					})
				}}
			>
				Duration: 50000
			</Button>

			<Button
				onClick={() => {
					toast.add({
						message: "closable",
						isClosable: true
					})
				}}
			>
				Closable
			</Button>

			<Button
				onClick={() => {
					toast.add({
						message: "with progress loader",
						withProgressLoader: true,
						duration: 15000
					})
				}}
			>
				With Progress Loader
			</Button>
		</div>
	)
}

export default function () {
	return (
		<Toaster>
			<ToastPreview />
		</Toaster>
	)
}
