// packages/react/src/lib/components/date-input/DateInput.tsx
import { forwardRef, InputHTMLAttributes, useRef } from "react"
import { classMapUtil } from "@fefade-ui/core/utils"
import styles from "@fefade-ui/core/styles/DateInput.module.css"

interface Props extends Omit<
	Omit<InputHTMLAttributes<HTMLInputElement>, "size">,
	"type"
> {
	type?: "date" | "month"
}

export default forwardRef<HTMLInputElement, Props>(
	({ className = "", type = "date", ...rest }, ref) => {
		const el = useRef<HTMLInputElement | null>(null)

		async function handleClick() {
			if (!el.current) {
				return
			}
			el.current.showPicker()
		}

		return (
			<input
				{...rest}
				ref={ref ?? el}
				className={classMapUtil(
					className,
					[className, styles],
					styles.dateInput
				)}
				type={type}
				onClick={handleClick}
			/>
		)
	}
)

// packages/svelte/src/lib/components/date-input/DateInput.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from "svelte/elements"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import styles from "@fefade-ui/core/styles/DateInput.module.css"

	interface Props extends Omit<HTMLInputAttributes, "type"> {
		type?: "date" | "month"
	}

	let { class: className = "", type = "date", ...rest }: Props = $props()

	let el: HTMLInputElement

	async function handleClick() {
		if (!el) return
		el.showPicker()
	}
</script>

<input
	{...rest}
	bind:this={el}
	class={classMapUtil(className, [className, styles], styles.dateInput)}
	{type}
	onclick={handleClick}
/>
