// packages/react/src/lib/components/image/Image.tsx
import type { ImageType } from "@fefade-ui/core/types"
import { forwardRef, ImgHTMLAttributes } from "react"
import { useAction } from "../../utils"
import { imageAction } from "@fefade-ui/core/actions"

interface Props
	extends Omit<ImgHTMLAttributes<Omit<HTMLImageElement, "src">>, "color">,
		ImageType {}

export default forwardRef<HTMLImageElement, Props>(
	({ className = "", lazy = false, dataSrc, fallback, ...rest }, _ref) => {
		const actionRef = useAction<
			HTMLImageElement,
			Parameters<typeof imageAction>[1]
		>(imageAction, { lazy })

		return (
			<img
				{...rest}
				ref={actionRef}
				className={className}
				data-src={dataSrc}
				data-fallback={fallback}
				loading={lazy ? "lazy" : undefined}
				decoding={lazy ? "async" : undefined}
			/>
		)
	}
)

// packages/svelte/src/lib/components/image/Image.svelte
<script lang="ts">
	import { imageAction } from "@fefade-ui/core/actions"
	import type { HTMLImgAttributes } from "svelte/elements"
	import type { ImageType } from "@fefade-ui/core/types"

	interface Props
		extends Omit<Omit<HTMLImgAttributes, "src">, "color">,
			ImageType {}

	let {
		class: className = "",
		lazy = false,
		dataSrc,
		fallback,
		...rest
	}: Props = $props()
</script>

<img
	{...rest}
	use:imageAction={{ lazy }}
	class={className}
	data-src={dataSrc}
	data-fallback={fallback}
	loading={lazy ? "lazy" : undefined}
	decoding={lazy ? "async" : undefined}
/>
