// packages/svelte/src/lib/components/bottom-sheet/BottomSheet.svelte
<script lang="ts">
	import { bottomSheetAction } from "@fefade-ui/core/actions"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import type { HTMLAttributes } from "svelte/elements"
	import type { BottomSheetType } from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/BottomSheet.module.css"

	interface Props
		extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
			BottomSheetType {}

	let {
		class: className = "",
		isOpen,
		handleClose,
		hideIn,
		children,
		...rest
	}: Props = $props()

	$effect(() => {
		if (isOpen) {
			document.body.style.overflow = "hidden"
			document.body.style.overscrollBehaviorY = "contain"
		} else {
			document.body.style.overflow = "auto"
			document.body.style.overscrollBehaviorY = "auto"
		}
	})
</script>

<div
	use:bottomSheetAction={{ handleClose, hideIn }}
	class={classMapUtil(className, [className, styles], styles.bottomSheet, {
		[styles.show]: isOpen
	})}
>
	<div {...rest} class={styles.wrapper}>
		{@render children?.()}
	</div>
</div>

// packages/react/src/lib/components/bottom-sheet/BottomSheet.tsx
import { classMapUtil } from "@fefade-ui/core/utils"
import { forwardRef, HTMLAttributes, useEffect } from "react"
import { useAction } from "../../utils"
import { bottomSheetAction } from "@fefade-ui/core/actions"
import type { BottomSheetType } from "@fefade-ui/core/types"
import styles from "@fefade-ui/core/styles/BottomSheet.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "color">, BottomSheetType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{ className = "", isOpen, handleClose, hideIn, children, ...rest },
		_ref
	) => {
		const actionRef = useAction<
			HTMLDivElement,
			Parameters<typeof bottomSheetAction>[1]
		>(bottomSheetAction, { handleClose, hideIn })

		useEffect(() => {
			if (isOpen) {
				document.body.style.overflow = "hidden"
				document.body.style.overscrollBehaviorY = "contain"
			} else {
				document.body.style.overflow = "auto"
				document.body.style.overscrollBehaviorY = "auto"
			}
		}, [isOpen])

		return (
			<div
				ref={actionRef}
				className={classMapUtil(
					className,
					[className, styles],
					styles.bottomSheet,
					{
						[styles.show]: isOpen
					}
				)}
			>
				<div {...rest} className={styles.wrapper}>
					{children}
				</div>
			</div>
		)
	}
)
