// packages/react/src/lib/components/avatar/Avatar.tsx
import { forwardRef, useState, type ImgHTMLAttributes } from "react"
import styles from "@fefade-ui/core/styles/Avatar.module.css"
import { classMapUtil } from "@fefade-ui/core/utils"
import type { AvatarType } from "@fefade-ui/core/types"

interface Props
	extends
		Omit<ImgHTMLAttributes<HTMLImageElement>, "width" | "height">,
		AvatarType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			width,
			height,
			textFallback,
			size = "md",
			grouped = false,
			children,
			...rest
		},
		ref
	) => {
		const [hasError, setHasError] = useState(false)

		function handleError() {
			setHasError(true)
		}

		return (
			<div
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					[size, styles],
					{ [styles.grouped]: grouped },
					styles.avatar
				)}
				style={{ width, height, ...rest.style }}
			>
				{!hasError && rest.src ? (
					<img {...rest} onError={handleError} />
				) : (
					textFallback && (
						<span className={styles.textFallback}>
							{textFallback.charAt(0).toUpperCase()}
						</span>
					)
				)}
				<span className={styles.textFallback}>{children}</span>
			</div>
		)
	}
)

// packages/svelte/src/lib/components/avatar/Avatar.svelte
<script lang="ts">
	import type { HTMLImgAttributes } from "svelte/elements"
	import { classMapUtil, mergeStyleUtil } from "@fefade-ui/core/utils"
	import styles from "@fefade-ui/core/styles/Avatar.module.css"
	import type { AvatarType } from "@fefade-ui/core/types"

	interface Props
		extends Omit<HTMLImgAttributes, "width" | "height">,
			AvatarType {}

	let {
		class: className = "",
		width,
		height,
		textFallback,
		size = "md",
		grouped = false,
		children,
		...rest
	}: Props = $props()

	let hasError = $state(false)

	function handleError() {
		hasError = true
	}
</script>

<div
	class={classMapUtil(
		className,
		[className, styles],
		[size, styles],
		{ [styles.grouped]: grouped },
		styles.avatar
	)}
	style={mergeStyleUtil(
		width && `width: ${width}`,
		height && `height: ${height}`,
		rest.style
	)}
>
	{#if !hasError && rest.src}
		<img {...rest} onerror={handleError} />
	{:else if textFallback}
		<span class={styles.textFallback}>
			{textFallback.charAt(0).toUpperCase()}
		</span>
	{/if}
	<span class={styles.textFallback}>
		{@render children?.()}
	</span>
</div>
