// packages/react/src/lib/components/toast/Toast.tsx
import {
	forwardRef,
	HTMLAttributes,
	useContext,
	useEffect,
	useState
} from "react"
import type { ToastType } from "@fefade-ui/core/types"
import { closeIcon } from "@fefade-ui/core/icons"
import { classMapUtil } from "@fefade-ui/core/utils"
import { Alert } from "../alert"
import { Button } from "../button"
import { ToastContext } from "../../contexts/ToastContext"
import { ProgressLoader } from "../progress-loader"
import styles from "@fefade-ui/core/styles/Toast.module.css"

interface Props
	extends Omit<Omit<HTMLAttributes<HTMLDivElement>, "color">, "id">,
		ToastType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			id,
			message,
			color = "info",
			isClosable = false,
			withProgressLoader = false,
			...rest
		},
		ref
	) => {
		const _toastContext = useContext(ToastContext)
		const toast = _toastContext.data.get(id)
		const duration = toast?.duration ?? 3000

		const [timerValue, setTimerValue] = useState(duration)
		const [paused, setPaused] = useState(false)

		useEffect(() => {
			const interval = setInterval(() => {
				setTimerValue((old) => {
					if (!paused && old > 0) {
						return Math.max(old - 100, 0)
					}
					return old
				})
			}, 100)

			return () => {
				clearInterval(interval)
			}
		}, [paused])

		useEffect(() => {
			if (timerValue <= 0) {
				_toastContext.remove(id)
			}
		}, [timerValue])

		return (
			<Alert
				{...rest}
				ref={ref}
				className={classMapUtil(className, styles.toast)}
				color={color}
				onMouseEnter={() => {
					setPaused(true)
				}}
				onMouseLeave={() => {
					setPaused(false)
				}}
			>
				<div className={styles.wrapper}>
					<div className={styles.message}>{message}</div>
					{withProgressLoader && (
						<ProgressLoader
							value={(timerValue / duration) * 100}
							color={color}
						/>
					)}
				</div>

				{isClosable && (
					<Button
						roundedFull
						size="xs"
						style={{
							padding: 0,
							height: "20px",
							minWidth: "20px"
						}}
						onClick={() => {
							_toastContext.remove(id)
						}}
					>
						<svg
							viewBox="0 -960 960 960"
							style={{
								display: "inline-block",
								verticalAlign: "middle",
								fill: "currentcolor",
								width: "16px",
								height: "16px"
							}}
						>
							<path d={closeIcon}></path>
						</svg>
					</Button>
				)}
			</Alert>
		)
	}
)

// packages/svelte/src/lib/components/toast/Toast.svelte
<script lang="ts">
	import type { ToastType } from "@fefade-ui/core/types"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import type { HTMLAttributes } from "svelte/elements"
	import Button from "../button/index.js"
	import { Alert } from "../alert/index.js"
	import { toastState } from "../../states/index.js"
	import ProgressLoader from "../progress-loader/index.js"
	import { closeIcon } from "@fefade-ui/core/icons"
	import styles from "@fefade-ui/core/styles/Toast.module.css"

	type Props = Omit<HTMLAttributes<HTMLDivElement>, "color" | "id"> & ToastType

	let {
		class: className = "",
		id,
		message,
		color = "info",
		isClosable = false,
		withProgressLoader = false,
		...rest
	}: Props = $props()

	const toast = toastState()
	const toastData = $derived(toast.data.get(id))
	const duration = $derived(toastData?.duration ?? 0)

	let timerValue = $state(0)
	let paused = $state(false)

	$effect(() => {
		const currentDuration = duration

		timerValue = currentDuration

		if (currentDuration <= 0) return

		const interval = setInterval(() => {
			if (!paused && timerValue > 0) {
				timerValue = Math.max(timerValue - 100, 0)
			}
		}, 100)

		return () => clearInterval(interval)
	})

	$effect(() => {
		if (duration > 0 && timerValue <= 0) {
			toast.remove(id)
		}
	})

	const progress = $derived(duration > 0 ? (timerValue / duration) * 100 : 0)
</script>

<Alert
	{...rest}
	class={classMapUtil(className, styles.toast)}
	onmouseenter={() => {
		paused = true
	}}
	onmouseleave={() => {
		paused = false
	}}
	{color}
>
	<div class={styles.wrapper}>
		<div class={styles.message}>
			{message}
		</div>
		{#if withProgressLoader}
			<ProgressLoader value={progress} {color} />
		{/if}
	</div>
	{#if isClosable}
		<Button
			roundedFull
			size="xs"
			style="
			padding: 0; 
			height: 20px;
			min-width: 20px;
			"
			onclick={() => {
				toast.remove(id)
			}}
		>
			<svg
				viewBox="0 -960 960 960"
				style="
				display: inline-block; 
				vertical-align: middle;
				fill: currentColor;
				width: 16px;
				height: 16px;
				"
			>
				<path d={closeIcon}></path>
			</svg>
		</Button>
	{/if}
</Alert>
