// packages/react/src/lib/components/toast/Toaster.tsx
import { CSSProperties, useState, type PropsWithChildren } from "react"
import type { AlignmentType, ToasterType } from "@fefade-ui/core/types"
import { ToastContext } from "../../contexts/ToastContext"
import { Constants } from "@fefade-ui/core"
import { classMapUtil } from "@fefade-ui/core/utils"
import Toast from "./Toast"
import styles from "@fefade-ui/core/styles/Toaster.module.css"

type Props = PropsWithChildren & {
	fullWidth?: boolean
}

export default function ({ fullWidth = false, children }: Props) {
	const [isHovered, setIsHovered] = useState(false)
	const [data, setData] = useState<Map<string, ToasterType>>(new Map())

	const maxToasts = Constants.MAX_TOASTS(fullWidth)

	function remove(id: string) {
		setData((prev) => {
			const newMap = new Map(prev)
			newMap.delete(id)
			return newMap
		})
	}

	function add(toast: ToasterType) {
		const id = crypto.randomUUID()
		const duration = toast.duration ?? Constants.TOAST_DEFAULT_DURATION
		const position = toast.position ?? "bottom-right"

		setData((old) => {
			const newMap = new Map(old)
			newMap.set(id, { ...toast, duration, position })
			return newMap
		})

		return id
	}

	function groupedData(alignment: AlignmentType) {
		return Array.from(data)
			.filter(([_, t]) => t.position === alignment)
			.slice(-maxToasts)
			.reverse()
	}

	return (
		<ToastContext.Provider value={{ data: data, add, remove }}>
			{Constants.alignments.map((alignment) => {
				const pos = alignment.split("-")[0]
				const isPositionTop = pos === "top"
				const grouped = groupedData(alignment)

				return (
					<div
						key={alignment}
						className={classMapUtil(
							[alignment, styles],
							[pos, styles],
							{
								[styles.fullWidth]: fullWidth
							},
							styles.toaster
						)}
					>
						{Array.from(grouped).map(([id, item], i) => (
							<div
								key={id}
								role="region"
								className={styles.wrapper}
								onMouseEnter={() => {
									setIsHovered(true)
								}}
								onMouseLeave={() => {
									setIsHovered(false)
								}}
								style={
									{
										["--toast-opacity"]: isHovered ? 1 : 1 - i * 0.08,
										["--toast-z-index"]: isHovered ? 1000 : 1000 - i,
										["--toast-translate"]: `${isPositionTop ? i * (isHovered ? 52 : 8) : -i * (isHovered ? 52 : 8)}px`,
										["--toast-scale"]: isHovered ? 1 : 1 - i * 0.05
									} as CSSProperties
								}
							>
								<Toast {...item} id={id} className={styles.toast} />
							</div>
						))}
					</div>
				)
			})}
			{children}
		</ToastContext.Provider>
	)
}

// packages/svelte/src/lib/components/toast/Toaster.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { toastState } from "../../states/index.js"
	import Toast from "./Toast.svelte"
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil, mergeStyleUtil } from "@fefade-ui/core/utils"
	import type { AlignmentType } from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/Toaster.module.css"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		fullWidth?: boolean
	}

	let {
		class: className = "",
		fullWidth = $bindable(false),
		...rest
	}: Props = $props()

	let isHovered = $state(false)

	const _toastState = toastState()
	const maxToasts = Constants.MAX_TOASTS(fullWidth)

	function groupedData(alignment: AlignmentType) {
		return Array.from(_toastState.data)
			.filter(([_, t]) => t.position === alignment)
			.slice(-maxToasts)
			.reverse()
	}
</script>

{#each Constants.alignments as alignment (alignment)}
	{@const pos = alignment.split("-")[0]}
	{@const isPositionTop = pos === "top"}
	{@const grouped = groupedData(alignment)}

	<div
		{...rest}
		class={classMapUtil(
			className,
			[className, styles],
			[alignment, styles],
			[pos, styles],
			{
				[styles.fullWidth]: fullWidth
			},
			styles.toaster
		)}
	>
		{#each grouped as [id, item], i (id)}
			<div
				role="region"
				class={styles.wrapper}
				onmouseenter={() => {
					isHovered = true
				}}
				onmouseleave={() => {
					isHovered = false
				}}
				style={mergeStyleUtil(
					`
						--toast-opacity: ${isHovered ? 1 : 1 - i * 0.08};
						--toast-z-index: ${isHovered ? 1000 : 1000 - i};
						--toast-translate: ${isPositionTop ? i * (isHovered ? 52 : 8) : -i * (isHovered ? 52 : 8)}px;
						--toast-scale: ${isHovered ? 1 : 1 - i * 0.05};
					`,
					rest.style
				)}
			>
				<Toast {...item} {id} class={styles.toast} />
			</div>
		{/each}
	</div>
{/each}
