// packages/svelte/src/lib/components/range-input/RangeInput.svelte
<script lang="ts">
	import type { RangeInputType } from "@fefade-ui/core/types"
	import {
		classMapUtil,
		mergeStyleUtil,
		dataIconUrlUtil
	} from "@fefade-ui/core/utils"
	import type { HTMLInputAttributes } from "svelte/elements"
	import { Constants } from "@fefade-ui/core"
	import styles from "@fefade-ui/core/styles/RangeInput.module.css"

	interface Props
		extends Omit<
				Omit<Omit<Omit<HTMLInputAttributes, "value">, "type">, "size">,
				"color"
			>,
			RangeInputType {}

	let {
		class: className = "",
		color = "primary",
		value = $bindable(0),
		icon,
		size = "md",
		showValue = true,
		min = 0,
		max = 100,
		...rest
	}: Props = $props()

	let bubbleActive = $state(false)

	const internalValue = $derived.by(() => {
		const minNum = Number(min)
		const maxNum = Number(max)
		const valueNum = Number(value)

		if (
			isNaN(minNum) ||
			isNaN(maxNum) ||
			isNaN(valueNum) ||
			maxNum === minNum
		) {
			return 0
		} else {
			return ((valueNum - minNum) / (maxNum - minNum)) * 100
		}
	})

	$effect(() => {
		if (bubbleActive) {
			document.body.style.overflow = "hidden"
			document.body.style.overscrollBehaviorY = "contain"
		} else {
			document.body.style.overflow = "auto"
			document.body.style.overscrollBehaviorY = "auto"
		}
	})
</script>

<div class={styles.wrapper}>
	<input
		{...rest}
		type="range"
		class={classMapUtil(
			className,
			[className, styles],
			[size, styles],
			[color, styles],
			styles.rangeInput
		)}
		style={mergeStyleUtil(
			`--internal-value: ${internalValue}%;`,
			icon && `--thumb-icon: url(${dataIconUrlUtil(icon)});`,
			"--rounded-full: 9999px;",
			"--thumb-size: 18px;",
			`--thumb-border: 2px solid ${Constants.themeColorVar.border};`,
			`--thumb-bg: ${Constants.themeColorVar.onSurface};`,
			"--track-height: 6px;",
			rest.style
		)}
		oninput={(e) => {
			rest.oninput?.(e)
			value = Number(e.currentTarget.value)
			bubbleActive = true
		}}
		ontouchend={() => {
			bubbleActive = false
		}}
		onmouseup={() => {
			bubbleActive = false
		}}
		{value}
		{min}
		{max}
	/>
	{#if showValue}
		<output
			class={classMapUtil(styles.bubble, { [styles.active]: bubbleActive })}
			style="left: calc({internalValue}% + ({8 - internalValue * 0.15}px))"
		>
			{internalValue.toFixed(0)}
		</output>
	{/if}
</div>

// packages/react/src/lib/components/range-input/RangeInput.tsx
import type { RangeInputType } from "@fefade-ui/core/types"
import { classMapUtil, dataIconUrlUtil } from "@fefade-ui/core/utils"
import {
	CSSProperties,
	forwardRef,
	InputHTMLAttributes,
	useMemo,
	useState
} from "react"
import { Constants } from "@fefade-ui/core"
import styles from "@fefade-ui/core/styles/RangeInput.module.css"

interface Props
	extends Omit<
			Omit<
				Omit<Omit<InputHTMLAttributes<HTMLInputElement>, "type">, "size">,
				"value"
			>,
			"color"
		>,
		RangeInputType {}

export default forwardRef<HTMLInputElement, Props>(
	(
		{
			className = "",
			color = "primary",
			icon,
			size = "md",
			showValue = true,
			min = 0,
			max = 100,
			...rest
		},
		ref
	) => {
		const [currentValue, setCurrentValue] = useState(rest.defaultValue ?? 0)
		const [bubbleActive, setBubbleActive] = useState(false)

		const isControlled = rest.value !== undefined
		const value = isControlled ? Number(rest.value) : currentValue

		const internalValue = useMemo(() => {
			const minNum = Number(min)
			const maxNum = Number(max)
			const valueNum = Number(value)

			if (
				isNaN(minNum) ||
				isNaN(maxNum) ||
				isNaN(valueNum) ||
				maxNum === minNum
			) {
				return 0
			} else {
				return ((valueNum - minNum) / (maxNum - minNum)) * 100
			}
		}, [min, max, value])

		return (
			<div className={styles.wrapper}>
				<input
					{...rest}
					ref={ref}
					className={classMapUtil(
						className,
						[className, styles],
						[size, styles],
						[color, styles],
						styles.rangeInput
					)}
					style={
						{
							["--internal-value"]: `${internalValue}%`,
							["--thumb-icon"]: icon && `url(${dataIconUrlUtil(icon)})`,
							["--rounded-full"]: "9999px",
							["--thumb-size"]: "18px",
							["--thumb-border"]: `2px solid ${Constants.themeColorVar.border}`,
							["--thumb-bg"]: `${Constants.themeColorVar.onSurface}`,
							["--track-height"]: "6px",
							...rest.style
						} as CSSProperties
					}
					value={internalValue}
					onChange={(e) => {
						if (isControlled) {
							rest.onChange?.(e)
						} else {
							setCurrentValue(Number(e.currentTarget.value))
						}
					}}
					onInput={() => {
						setBubbleActive(true)
					}}
					onTouchEnd={() => {
						setBubbleActive(false)
					}}
					onMouseUp={() => {
						setBubbleActive(false)
					}}
					type="range"
					min={min}
					max={max}
				/>
				{showValue && (
					<output
						className={classMapUtil(styles.bubble, {
							[styles.active]: bubbleActive
						})}
						style={{
							left: `calc(${internalValue}% + (${8 - internalValue * 0.15}px))`
						}}
					>
						{internalValue.toFixed(0)}
					</output>
				)}
			</div>
		)
	}
)
