// packages/svelte/src/lib/components/drawer/Drawer.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import type { DrawerType } from "@fefade-ui/core/types"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import styles from "@fefade-ui/core/styles/Drawer.module.css"

	interface Props extends HTMLAttributes<HTMLDivElement>, DrawerType {}

	let {
		class: className = "",
		isOpen = false,
		variant = "temporary",
		position = "left",
		children,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(
		className,
		[className, styles],
		styles.drawer,
		[position, styles],
		[variant, styles],
		{
			[styles.show]: isOpen
		}
	)}
>
	{@render children?.()}
</div>

// packages/react/src/lib/components/drawer/Drawer.tsx
import React, { forwardRef } from "react"
import { classMapUtil } from "@fefade-ui/core/utils"
import type { DrawerType } from "@fefade-ui/core/types"
import styles from "@fefade-ui/core/styles/Drawer.module.css"

export interface Props
	extends React.HTMLAttributes<HTMLDivElement>,
		DrawerType {}

export default forwardRef<HTMLDivElement, Props>((props, ref) => {
	const {
		className = "",
		isOpen = false,
		variant = "temporary",
		position = "left",
		children,
		...rest
	} = props

	return (
		<div
			{...rest}
			ref={ref}
			className={classMapUtil(
				className,
				[className, styles],
				styles.drawer,
				[position, styles],
				[variant, styles],
				{
					[styles.show]: isOpen
				}
			)}
		>
			{children}
		</div>
	)
})
