// packages/react/src/lib/components/checkbox/Checkbox.tsx
import { forwardRef, InputHTMLAttributes } from "react"
import type { CheckboxType } from "@fefade-ui/core/types"
import { classMapUtil } from "@fefade-ui/core/utils"
import { checkmarkIcon } from "@fefade-ui/core/icons"
import styles from "@fefade-ui/core/styles/Checkbox.module.css"

interface Props
	extends
		Omit<
			Omit<Omit<InputHTMLAttributes<HTMLInputElement>, "size">, "type">,
			"color"
		>,
		CheckboxType {}

export default forwardRef<HTMLInputElement, Props>(
	(
		{ className = "", label, size = "sm", color = "secondary", ...rest },
		ref
	) => {
		return (
			<label
				className={classMapUtil(
					className,
					[className, styles],
					[size, styles],
					[color, styles],
					{
						["muted"]: rest.disabled
					},
					styles.checkbox
				)}
			>
				<input
					{...rest}
					ref={ref}
					readOnly={rest.readOnly ?? rest.checked}
					type="checkbox"
				/>
				<div className={styles.wrapper}>
					<div className={styles.bg}></div>
					<svg
						className={styles.icon}
						viewBox="0 0 24 24"
						style={{
							display: "inline-block",
							verticalAlign: "middle"
						}}
						fill="none"
					>
						<path
							strokeLinejoin="round"
							strokeLinecap="round"
							strokeWidth="3"
							stroke="currentColor"
							d={checkmarkIcon}
						></path>
					</svg>
				</div>
				{label && label}
			</label>
		)
	}
)

// packages/svelte/src/lib/components/checkbox/Checkbox.svelte
<script lang="ts">
	import { classMapUtil } from "@fefade-ui/core/utils"
	import type { HTMLInputAttributes } from "svelte/elements"
	import type { CheckboxType } from "@fefade-ui/core/types"
	import { checkmarkIcon } from "@fefade-ui/core/icons"
	import styles from "@fefade-ui/core/styles/Checkbox.module.css"

	interface Props
		extends
			Omit<Omit<Omit<HTMLInputAttributes, "size">, "type">, "color">,
			CheckboxType {}

	let {
		class: className = "",
		label,
		size = "sm",
		color = "secondary",
		...rest
	}: Props = $props()
</script>

<label
	class={classMapUtil(
		className,
		[className, styles],
		[size, styles],
		[color, styles],
		{
			["muted"]: rest.disabled
		},
		styles.checkbox
	)}
>
	<input {...rest} readonly={rest.readonly ?? rest.checked} type="checkbox" />
	<div class={styles.wrapper}>
		<div class={styles.bg}></div>
		<svg
			class={styles.icon}
			viewBox="0 0 24 24"
			style="
			display: inline-block; 
			vertical-align: middle;
			"
			fill="none"
		>
			<path
				stroke-linejoin="round"
				stroke-linecap="round"
				stroke-width="3"
				stroke="currentColor"
				d={checkmarkIcon}
			></path>
		</svg>
	</div>
	{#if label}
		{label}
	{/if}
</label>
