// packages/svelte/src/lib/components/number-input/NumberInput.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from "svelte/elements"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import Button from "../button/index.js"
	import type { NumberInputType } from "@fefade-ui/core/types"
	import { onMount, tick } from "svelte"
	import { fly } from "svelte/transition"
	import styles from "@fefade-ui/core/styles/NumberInput.module.css"

	interface Props
		extends
			Omit<
				Omit<Omit<Omit<HTMLInputAttributes, "step">, "value">, "type">,
				"size"
			>,
			NumberInputType {}

	let {
		class: className = "",
		variant = "contained",
		value = $bindable(0),
		onChange,
		autoFocus = false,
		step,
		size = "md",
		...rest
	}: Props = $props()

	let el: HTMLInputElement | undefined = $state()
	let delay = $state(1)

	function increment() {
		if (rest.disabled || (rest.max !== undefined && value >= Number(rest.max)))
			return
		value = step ? value + step : value + 1
		onChange?.(value)
		delay = 1
	}

	function decrement() {
		if (rest.disabled || (rest.min !== undefined && value <= Number(rest.min)))
			return
		value = step ? value - step : value - 1
		onChange?.(value)
		delay = -1
	}

	async function handleKeydown(
		e: KeyboardEvent & {
			currentTarget: EventTarget & HTMLInputElement
		}
	) {
		if (e.key === "ArrowUp") {
			e.preventDefault()
			increment()
		} else if (e.key === "ArrowDown") {
			e.preventDefault()
			decrement()
		}

		await tick()
		handleFocus()
	}

	function handleFocus() {
		if (el && !rest.readonly) {
			el.focus()
		}
	}

	function handleWheel(
		e: WheelEvent & {
			currentTarget: EventTarget & HTMLInputElement
		}
	) {
		if (e.deltaY > 0) {
			decrement()
		} else if (e.deltaY < 0) {
			increment()
		}
	}

	onMount(() => {
		if (autoFocus) handleFocus()
		value = rest.min !== undefined ? Number(rest.min) : value
	})
</script>

<div
	role="button"
	tabindex="0"
	class={classMapUtil(
		className,
		[className, styles],
		[variant, styles],
		[size, styles],
		styles.numberInput
	)}
	style={rest.style}
>
	<Button
		aria-label="Decrement"
		{variant}
		{size}
		disabled={value === rest.min || rest.disabled}
		onclick={decrement}
	>
		-
	</Button>

	<div class={styles.wrapper}>
		{#key value}
			<input
				{...rest}
				class={styles.input}
				bind:this={el}
				type="number"
				{value}
				onkeydown={handleKeydown}
				in:fly={{ y: delay * -15, duration: 200 }}
				out:fly={{ y: delay * 15, duration: 100 }}
				onwheel={handleWheel}
				style={undefined}
			/>
		{/key}
	</div>
	<Button
		aria-label="Increment"
		{variant}
		{size}
		disabled={value === rest.max || rest.disabled}
		onclick={increment}
	>
		+
	</Button>
</div>

// packages/react/src/lib/components/number-input/NumberInput.tsx
import React, {
	forwardRef,
	useRef,
	useEffect,
	useCallback,
	KeyboardEvent,
	WheelEvent,
	InputHTMLAttributes
} from "react"
import { classMapUtil } from "@fefade-ui/core/utils"
import type { NumberInputType } from "@fefade-ui/core/types"
import styles from "@fefade-ui/core/styles/NumberInput.module.css"
import { Button } from "../button"

interface Props
	extends
		Omit<
			Omit<
				Omit<
					Omit<Omit<InputHTMLAttributes<HTMLInputElement>, "onChange">, "step">,
					"value"
				>,
				"type"
			>,
			"size"
		>,
		NumberInputType {}

export default forwardRef<HTMLInputElement, Props>(
	(
		{
			className = "",
			variant = "contained",
			value = 0,
			onChange,
			autoFocus = false,
			step,
			size = "md",
			...rest
		},
		ref
	) => {
		const internalRef = useRef<HTMLInputElement | null>(null)
		const inputRef = (ref as React.RefObject<HTMLInputElement>) || internalRef

		const noCanIncrement = (v: number) => {
			return rest.disabled || (rest.max !== undefined && v >= Number(rest.max))
		}

		const noCanDecrement = (v: number) => {
			return rest.disabled || (rest.min !== undefined && v <= Number(rest.min))
		}

		const handleFocus = useCallback(() => {
			if (inputRef.current && !rest.readOnly) {
				inputRef.current.focus()
			}
		}, [inputRef, rest.readOnly])

		const setValue = useCallback(
			(newValue: number) => {
				onChange?.(newValue)
			},
			[onChange]
		)

		const increment = useCallback(() => {
			if (noCanIncrement(value)) {
				return
			}

			const newValue = step ? value + step : value + 1
			setValue(newValue)
		}, [value, step, rest.disabled, rest.max, setValue])

		const decrement = useCallback(() => {
			if (noCanDecrement(value)) {
				return
			}

			const newValue = step ? value - step : value - 1
			setValue(newValue)
		}, [value, step, rest.disabled, rest.min, setValue])

		const handleKeydown = useCallback(
			(e: KeyboardEvent<HTMLInputElement>) => {
				if (e.key === "ArrowUp") {
					e.preventDefault()
					increment()
				} else if (e.key === "ArrowDown") {
					e.preventDefault()
					decrement()
				}
				handleFocus()
			},
			[increment, decrement, handleFocus]
		)

		const handleWheel = useCallback(
			(e: WheelEvent<HTMLInputElement>) => {
				if (e.deltaY > 0) {
					decrement()
				} else if (e.deltaY < 0) {
					increment()
				}
			},
			[increment, decrement]
		)

		useEffect(() => {
			if (autoFocus) handleFocus()
			if (rest.min !== undefined && value < Number(rest.min)) {
				setValue(Number(rest.min))
			}
		}, [autoFocus, handleFocus, rest.min, setValue, value])

		return (
			<div
				role="button"
				tabIndex={0}
				className={classMapUtil(
					className,
					[className, styles],
					[variant, styles],
					[size, styles],
					styles.numberInput
				)}
				style={rest.style}
			>
				<Button
					aria-label="Decrement"
					variant={variant}
					size={size}
					disabled={value === rest.min || rest.disabled}
					onClick={decrement}
				>
					-
				</Button>

				<div className={styles.wrapper}>
					<input
						{...rest}
						ref={inputRef}
						type="number"
						value={value}
						onChange={(e) => {
							const newValue = Number(e.target.value)
							// if (noCanIncrement(newValue) || noCanDecrement(newValue)) {
							// 	return
							// }
							setValue(newValue)
						}}
						onKeyDown={handleKeydown}
						onWheel={handleWheel}
						className={styles.input}
					/>
				</div>

				<Button
					aria-label="Increment"
					variant={variant}
					size={size}
					disabled={value === rest.max || rest.disabled}
					onClick={increment}
				>
					+
				</Button>
			</div>
		)
	}
)
