// packages/svelte/src/lib/components/card/Card.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import type { HTMLAttributes } from "svelte/elements"
	import {
		classMapUtil,
		getPropValueUtil,
		handleClickUtil,
		mergeStyleUtil,
		normalizeSizeUtil
	} from "@fefade-ui/core/utils"
	import { glowOnHoverAction } from "@fefade-ui/core/actions"
	import type { CardType, HTMLAttrAnchor } from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/Card.module.css"

	interface Props
		extends
			Omit<HTMLAttributes<HTMLDivElement>, "color">,
			CardType,
			HTMLAttrAnchor {}

	let {
		class: className = "",
		isTranslucent = false,
		glowOnHover = false,
		animatedBorder = $bindable(),
		variant = "outlined",
		href,
		target = "_self",
		download,
		children,
		...rest
	}: Props = $props()

	const borderStopOnHover = getPropValueUtil<
		{ stopOnHover?: boolean },
		"stopOnHover"
	>(animatedBorder, "stopOnHover", false)

	const borderWidth = $derived(
		getPropValueUtil<{ width?: string }, "width">(
			animatedBorder,
			"width",
			"1px"
		)
	)

	const borderPrimaryColor = $derived(
		getPropValueUtil<{ primaryColor?: string }, "primaryColor">(
			animatedBorder,
			"primaryColor",
			Constants.themeColorVar.onSurface
		)
	)

	const borderSecondaryColor = $derived(
		getPropValueUtil<{ secondaryColor?: string }, "secondaryColor">(
			animatedBorder,
			"secondaryColor",
			Constants.themeColorVar.border
		)
	)
</script>

{#snippet component()}
	<div
		{...rest}
		role="button"
		class={classMapUtil(
			className,
			[className, styles],
			[variant, styles],
			styles.card,
			{
				[styles.isTranslucent]: isTranslucent,
				[styles.animatedBorder]: Boolean(animatedBorder),
				[styles.stopOnHover]: Boolean(borderStopOnHover),
				["clickable"]: rest.onclick || href
			}
		)}
		style={mergeStyleUtil(
			`--border-width: ${normalizeSizeUtil(borderWidth!)}`,
			`--primary: ${borderPrimaryColor};`,
			`--secondary: ${borderSecondaryColor};`,
			rest.style
		)}
		onclick={(e) => {
			handleClickUtil({
				href,
				download,
				target,
				onClick: () => {
					rest.onclick?.(e)
				}
			})
		}}
	>
		{@render children?.()}
	</div>
{/snippet}

{#if glowOnHover}
	<div use:glowOnHoverAction>
		{@render component()}
	</div>
{:else}
	{@render component()}
{/if}

// packages/react/src/lib/components/card/Card.tsx
import { Constants } from "@fefade-ui/core"
import type { CardType, HTMLAttrAnchor } from "@fefade-ui/core/types"
import {
	classMapUtil,
	getPropValueUtil,
	handleClickUtil,
	normalizeSizeUtil
} from "@fefade-ui/core/utils"
import { CSSProperties, forwardRef, HTMLAttributes } from "react"
import { useAction } from "../../utils"
import { glowOnHoverAction } from "@fefade-ui/core/actions"
import styles from "@fefade-ui/core/styles/Card.module.css"

interface Props
	extends
		Omit<HTMLAttributes<HTMLDivElement>, "color">,
		CardType,
		HTMLAttrAnchor {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			isTranslucent = false,
			glowOnHover = false,
			animatedBorder = false,
			variant = "outlined",
			href,
			target = "_self",
			download,
			children,
			...rest
		},
		ref
	) => {
		const actionRef = glowOnHover
			? useAction<HTMLDivElement>(glowOnHoverAction)
			: undefined

		const borderStopOnHover = getPropValueUtil<
			{ stopOnHover?: boolean },
			"stopOnHover"
		>(animatedBorder, "stopOnHover", false)

		const borderWidth = getPropValueUtil<{ width?: string }, "width">(
			animatedBorder,
			"width",
			"1px"
		)

		const borderPrimaryColor = getPropValueUtil<
			{ primaryColor?: string },
			"primaryColor"
		>(animatedBorder, "primaryColor", Constants.themeColorVar.onSurface)

		const borderSecondaryColor = getPropValueUtil<
			{ secondaryColor?: string },
			"secondaryColor"
		>(animatedBorder, "secondaryColor", Constants.themeColorVar.border)

		function handleClick(e: any) {
			handleClickUtil({
				href,
				download,
				target,
				onClick: () => {
					rest.onClick?.(e)
				}
			})
		}

		return (
			<div ref={actionRef} style={{ margin: 0 }}>
				<div
					{...rest}
					ref={ref}
					role="button"
					className={classMapUtil(
						className,
						[className, styles],
						[variant, styles],
						styles.card,
						{
							[styles.isTranslucent]: isTranslucent,
							[styles.animatedBorder]: Boolean(animatedBorder),
							[styles.stopOnHover]: Boolean(borderStopOnHover),
							["clickable"]: rest.onClick || href
						}
					)}
					style={
						{
							"--border-width": normalizeSizeUtil(borderWidth!),
							"--primary": borderPrimaryColor,
							"--secondary": borderSecondaryColor,
							...rest.style
						} as CSSProperties
					}
					onClick={handleClick}
				>
					{children}
				</div>
			</div>
		)
	}
)
