// packages/react/src/lib/components/modal/ModalHeader.tsx
import type { AlignType } from "@fefade-ui/core/types"
import { classMapUtil } from "@fefade-ui/core/utils"
import { forwardRef, HTMLAttributes } from "react"
import { Button } from "../button"
import { closeIcon } from "@fefade-ui/core/icons"
import styles from "@fefade-ui/core/styles/ModalHeader.module.css"

interface Props extends Omit<HTMLAttributes<HTMLDivElement>, "color"> {
	align?: AlignType
	handleClose?: () => void
}

export default forwardRef<HTMLDivElement, Props>(
	(
		{ className = "", align = "start", handleClose, children, ...rest },
		ref
	) => {
		return (
			<div
				{...rest}
				ref={ref}
				className={classMapUtil(className, [className, styles], styles.header)}
			>
				<div
					className={styles.content}
					style={{ justifyContent: align, ...rest.style }}
				>
					{children}
				</div>
				{handleClose && (
					<Button variant="text" onClick={handleClose}>
						<svg
							viewBox="0 -960 960 960"
							style={{
								display: "inline-block",
								verticalAlign: "middle",
								fill: "currentcolor",
								width: "24px",
								height: "24px"
							}}
						>
							<path d={closeIcon}></path>
						</svg>
					</Button>
				)}
			</div>
		)
	}
)

// packages/svelte/src/lib/components/modal/ModalHeader.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import Button from "../button/index.js"
	import type { AlignType } from "@fefade-ui/core/types"
	import { closeIcon } from "@fefade-ui/core/icons"
	import styles from "@fefade-ui/core/styles/ModalHeader.module.css"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		align?: AlignType
		handleClose?: () => void
	}

	let {
		class: className = "",
		align = "start",
		handleClose,
		children,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(className, [className, styles], styles.header)}
>
	<div class={styles.content} style="justify-content: {align};">
		{@render children?.()}
	</div>
	{#if handleClose}
		<Button variant="text" onclick={handleClose}>
			<svg
				viewBox="0 -960 960 960"
				style="
				display: inline-block; 
				vertical-align: middle;
				fill: currentColor;
				width: 24px;
				height: 24px;
				"
			>
				<path d={closeIcon}></path>
			</svg>
		</Button>
	{/if}
</div>
