// packages/react/src/lib/components/modal/ModalActions.tsx
import type { AlignType } from "@fefade-ui/core/types"
import { classMapUtil } from "@fefade-ui/core/utils"
import { CSSProperties, forwardRef, HTMLAttributes } from "react"
import styles from "@fefade-ui/core/styles/ModalActions.module.css"

interface Props extends Omit<HTMLAttributes<HTMLDivElement>, "color"> {
	align?: AlignType
}

export default forwardRef<HTMLDivElement, Props>(
	({ className = "", align = "end", children, ...rest }, ref) => {
		return (
			<div
				{...rest}
				ref={ref}
				className={classMapUtil(className, [className, styles], styles.actions)}
				style={
					{
						["--align"]: align,
						...rest.style
					} as CSSProperties
				}
			>
				{children}
			</div>
		)
	}
)

// packages/svelte/src/lib/components/modal/ModalActions.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil, mergeStyleUtil } from "@fefade-ui/core/utils"
	import type { AlignType } from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/ModalActions.module.css"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		align?: AlignType
	}

	let {
		class: className = "",
		align = "end",
		children,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(className, [className, styles], styles.actions)}
	style={mergeStyleUtil(`--align: ${align};`, rest.style)}
>
	{@render children?.()}
</div>
