// packages/react/src/lib/components/modal/Modal.tsx
import type { ModalType } from "@fefade-ui/core/types"
import { classMapUtil } from "@fefade-ui/core/utils"
import { forwardRef, HTMLAttributes, useEffect, useRef, useState } from "react"
import { Card } from "../card"
import styles from "@fefade-ui/core/styles/Modal.module.css"
import animationStyle from "@fefade-ui/core/styles/Animation.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "color">, ModalType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			isOpen,
			handleClose,
			variant = "contained",
			children,
			...rest
		},
		ref
	) => {
		const [show, setShow] = useState(false)

		const el = useRef<HTMLDivElement | null>(null)

		useEffect(() => {
			if (isOpen) {
				el.current?.focus()
				setShow(true)
			}
		}, [isOpen])

		if (!show) return null

		return (
			<div
				className={classMapUtil(className, [className, styles], styles.modal)}
			>
				<div
					ref={ref ?? el}
					className={classMapUtil(styles.overlay, {
						[animationStyle.fadeIn]: isOpen,
						[animationStyle.fadeOut]: !isOpen
					})}
					role="alertdialog"
					tabIndex={0}
					onKeyDown={(e) => {
						if (e.key === "Escape" || e.key === " ") {
							handleClose()
						}
					}}
					onClick={(e) => {
						if (e.target === e.currentTarget) {
							handleClose()
						}
					}}
					onAnimationEnd={() => {
						if (!isOpen) {
							setShow(false)
						}
					}}
				>
					<div
						className={classMapUtil(styles.wrapper, {
							[animationStyle.scaleIn]: isOpen,
							[animationStyle.scaleOut]: !isOpen
						})}
					>
						<Card {...rest} className={styles.content} variant={variant}>
							{children}
						</Card>
					</div>
				</div>
			</div>
		)
	}
)

// packages/svelte/src/lib/components/modal/Modal.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import Card from "../card/index.js"
	import type { ModalType } from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/Modal.module.css"
	import animationStyle from "@fefade-ui/core/styles/Animation.module.css"

	interface Props extends ModalType, HTMLAttributes<HTMLDivElement> {}

	let {
		class: className = "",
		isOpen,
		handleClose,
		variant = "contained",
		children,
		...rest
	}: Props = $props()

	let show = $state(false)
	let el: HTMLDivElement | undefined = $state()

	$effect(() => {
		if (isOpen) {
			el?.focus()
			show = true
		}
	})
</script>

{#if show}
	<div class={classMapUtil(className, [className, styles], styles.modal)}>
		<div
			bind:this={el}
			class={classMapUtil(styles.overlay, {
				[animationStyle.fadeIn]: isOpen,
				[animationStyle.fadeOut]: !isOpen
			})}
			role="alertdialog"
			tabindex="0"
			onkeydown={(e) => {
				if (e.key === "Escape" || e.key === " ") {
					handleClose()
				}
			}}
			onclick={(e) => {
				if (e.target === e.currentTarget) {
					handleClose()
				}
			}}
			onanimationend={() => {
				if (!isOpen) {
					show = false
				}
			}}
		>
			<div
				class={classMapUtil(styles.wrapper, {
					[animationStyle.scaleIn]: isOpen,
					[animationStyle.scaleOut]: !isOpen
				})}
			>
				<Card {...rest} class={styles.content} {variant}>
					{@render children?.()}
				</Card>
			</div>
		</div>
	</div>
{/if}
