// packages/docs/src/lib/components/SpinnerPreview.tsx
import { Constants } from "@fefade-ui/core"
import { Spinner } from "@fefade-ui/react"

export default function () {
	return (
		<div
			style={{
				display: "flex",
				flexWrap: "wrap",
				alignItems: "baseline",
				gap: "1.5rem"
			}}
		>
			{Constants.statusColors.map((color) => (
				<div
					key={`color-${color}`}
					style={{
						display: "flex",
						flexDirection: "column",
						alignItems: "center"
					}}
				>
					<Spinner className={`text-on-${color}`} size="md" />
					<span>{color}</span>
				</div>
			))}

			{Constants.sizes.map((size) => (
				<div
					key={`size-${size}`}
					style={{
						display: "flex",
						flexDirection: "column",
						alignItems: "center"
					}}
				>
					<Spinner size={size} color="primary" />
					<span>{size}</span>
				</div>
			))}
		</div>
	)
}

// apps/docs/src/lib/components/SpinnerPreview.vue
<script setup lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { Spinner } from "@fefade-ui/vue"
</script>

<template>
	<div
		style="display: flex; flex-wrap: wrap; align-items: baseline; gap: 1.5rem"
	>
		<div
			v-for="color in Constants.statusColors"
			:key="`color-${color}`"
			style="display: flex; flex-direction: column; align-items: center"
		>
			<Spinner :class="`text-on-${color}`" size="md" />
			<span>{{ color }}</span>
		</div>

		<div
			v-for="size in Constants.sizes"
			:key="`size-${size}`"
			style="display: flex; flex-direction: column; align-items: center"
		>
			<Spinner :size="size" color="primary" />
			<span>{{ size }}</span>
		</div>
	</div>
</template>
