// apps/docs/src/lib/components/StatusPreview.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import { Status, themeConfig } from "@fefade-ui/svelte"

	const { colors } = $derived(themeConfig())
</script>

<div style="max-width: 300px; margin: 0 auto; line-height: 3;">
	{#each Constants.statusVariants as variant, i (variant)}
		<Status {variant} color={i % 2 ? colors.success : colors.error} />
		<br />
	{/each}

	{#each ["5rem", 100, "150px", 200] as size, i (i)}
		<Status
			color={i % 2 ? colors.info : colors.warning}
			variant={i % 2 ? "bounce" : "none"}
			{size}
		/>
		<br />
	{/each}
</div>

// apps/docs/src/lib/components/StatusPreview.tsx
import { Status } from "@fefade-ui/react"
import { Constants } from "@fefade-ui/core"

export default function () {
	return (
		<div
			style={{
				maxWidth: "300px",
				margin: "0 auto",
				lineHeight: 3
			}}
		>
			{Constants.statusVariants.map((variant, i) => (
				<div key={variant}>
					<Status
						variant={variant}
						color={
							i % 2
								? Constants.themeColorVar.success
								: Constants.themeColorVar.error
						}
					/>
					<br />
				</div>
			))}

			{["5rem", 100, "150px", 200].map((size, i) => (
				<div key={size}>
					<Status
						color={
							i % 2
								? Constants.themeColorVar.info
								: Constants.themeColorVar.warning
						}
						variant={i % 2 ? "bounce" : "none"}
						size={size}
					/>
					<br />
				</div>
			))}
		</div>
	)
}
