// packages/docs/src/lib/components/UseMediaQueryPreview.svelte
<script lang="ts">
	import { useMediaQuery } from "@fefade-ui/svelte"

	const isSm = useMediaQuery("max-width", "sm")
	const isMd = useMediaQuery("max-width", "md")
	const isCustom = useMediaQuery("max-width", "800px")
</script>

<h4>sm (425px): {isSm.value}</h4>
<h4>md (768px): {isMd.value}</h4>
<h4>custom (800px): {isCustom.value}</h4>

// apps/docs/src/lib/components/UseMediaQueryPreview.tsx
import { useMediaQuery } from "@fefade-ui/react"

export default function () {
	const isSm = useMediaQuery("max-width", "sm")
	const isMd = useMediaQuery("max-width", "md")
	const isCustom = useMediaQuery("max-width", "800px")

	return (
		<>
			<h4>sm (425px): {String(isSm)}</h4>
			<h4>md (768px): {String(isMd)}</h4>
			<h4>custom (800px): {String(isCustom)}</h4>
		</>
	)
}
