// packages/svelte/src/lib/components/switch/Switch.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import type { SwitchType } from "@fefade-ui/core/types"
	import type { HTMLInputAttributes } from "svelte/elements"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import type { Snippet } from "svelte"
	import { mergeStyleUtil, getPropValueUtil } from "@fefade-ui/core/utils"
	import styles from "@fefade-ui/core/styles/Switch.module.css"

	interface Props
		extends Omit<Omit<HTMLInputAttributes, "size">, "type">,
			SwitchType {
		label?: string | Snippet<[]>
	}

	let {
		class: className = "",
		size = "sm",
		label,
		indicatorColor = {
			unchecked: Constants.themeColorVar.onSurface,
			checked: Constants.themeColorVar.onPrimary
		},
		checked = $bindable(false),
		children,
		...rest
	}: Props = $props()

	const uncheckedColor = $derived(
		getPropValueUtil<{ unchecked?: string }, "unchecked">(
			indicatorColor,
			"unchecked",
			Constants.themeColorVar.onSurface
		)
	)

	const checkedColor = $derived(
		getPropValueUtil<{ checked?: string }, "checked">(
			indicatorColor,
			"checked",
			Constants.themeColorVar.onPrimary
		)
	)
</script>

<div class={styles.switch}>
	<label
		for={rest.id ?? rest.name}
		class={classMapUtil(
			className,
			[className, styles],
			[size, styles],
			styles.content
		)}
	>
		<input
			{...rest}
			hidden
			style={undefined}
			type="checkbox"
			{checked}
			oninput={(e) => {
				checked = e.currentTarget.checked
			}}
		/>
		<span
			class={styles.slider}
			style={mergeStyleUtil(
				`--bg-unchecked: ${uncheckedColor};`,
				`--bg-checked: ${checkedColor};`,
				rest.style
			)}
		>
			{@render children?.()}
		</span>
	</label>
	{#if typeof label === "string"}
		{label}
	{:else}
		{@render label?.()}
	{/if}
</div>

// packages/react/src/lib/components/switch/Switch.tsx
import { Constants } from "@fefade-ui/core"
import type { SwitchType } from "@fefade-ui/core/types"
import { classMapUtil, getPropValueUtil } from "@fefade-ui/core/utils"
import {
	CSSProperties,
	forwardRef,
	InputHTMLAttributes,
	ReactNode
} from "react"
import styles from "@fefade-ui/core/styles/Switch.module.css"

interface Props
	extends Omit<InputHTMLAttributes<HTMLInputElement>, "size">, SwitchType {
	label?: string | ReactNode
}

export default forwardRef<HTMLInputElement, Props>(
	(
		{
			className = "",
			size = "sm",
			label,
			indicatorColor = {
				unchecked: Constants.themeColorVar.onSurface,
				checked: Constants.themeColorVar.onPrimary
			},
			children,
			...rest
		},
		ref
	) => {
		const uncheckedColor = getPropValueUtil<
			{ unchecked?: string },
			"unchecked"
		>(indicatorColor, "unchecked", Constants.themeColorVar.onSurface)

		const checkedColor = getPropValueUtil<{ checked?: string }, "checked">(
			indicatorColor,
			"checked",
			Constants.themeColorVar.onPrimary
		)

		return (
			<div className={styles.switch}>
				<label
					htmlFor={rest.id}
					className={classMapUtil(
						className,
						[className, styles],
						[size, styles],
						styles.content
					)}
				>
					<input {...rest} ref={ref} hidden style={undefined} type="checkbox" />
					<span
						className={styles.slider}
						style={
							{
								["--bg-unchecked"]: uncheckedColor,
								["--bg-checked"]: checkedColor,
								...rest.style
							} as CSSProperties
						}
					>
						{children}
					</span>
				</label>
				{label}
			</div>
		)
	}
)
