// packages/svelte/src/lib/components/gallery/GalleryImage.svelte
<script lang="ts">
	import {
		classMapUtil,
		handleClickUtil,
		styleToStringUtil
	} from "@fefade-ui/core/utils"
	import type {
		CSSKebabType,
		GalleryItemType,
		HTMLAttrAnchor,
		ImageType
	} from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/GalleryItem.module.css"
	import type { HTMLImgAttributes } from "svelte/elements"
	import { Image } from "../image/index.js"
	import { createPortalAction } from "@fefade-ui/core/actions"
	import Modal from "../modal/index.js"

	type HTMLImageAttr = Omit<HTMLImgAttributes, "src">

	interface Props
		extends HTMLImageAttr,
			GalleryItemType<CSSKebabType, HTMLImageAttr>,
			HTMLAttrAnchor,
			ImageType {}

	let {
		class: className = "",
		lazy = false,
		dataSrc,
		href,
		target = "_self",
		download,
		viewer,
		captionStyle,
		children,
		...rest
	}: Props = $props()

	let openModal = $state(false)
	let selectedEl: HTMLImageElement | undefined = $state()

	function handleClick(e: any) {
		handleClickUtil({
			href,
			download,
			target,
			onClick: () => {
				rest.onclick?.(e)
			}
		})
	}

	function handleImageClick(
		e: MouseEvent & { currentTarget: EventTarget & HTMLImageElement }
	) {
		if (viewer) {
			selectedEl = e.currentTarget
			openModal = true
		}

		handleClick(e)
	}
</script>

{#if viewer && openModal && selectedEl}
	<div use:createPortalAction>
		<Modal
			isOpen={openModal}
			style="border: none;"
			handleClose={() => {
				openModal = false
				selectedEl = undefined
			}}
		>
			<Modal.Content
				style="
				text-align: center; 
				overflow: hidden; 
				padding: 0;
				"
			>
				<img
					{...rest}
					{...viewer}
					src={selectedEl.dataset.dataSrc ?? selectedEl.src}
				/>
			</Modal.Content>
		</Modal>
	</div>
{/if}

<figure
	class={classMapUtil(className, [className, styles], styles.galleryItem, {
		["clickable"]: rest.onclick || viewer || href
	})}
>
	<Image
		{...rest}
		class={styles.thumbnail}
		{lazy}
		{dataSrc}
		onclick={handleImageClick}
	/>

	<figcaption class={styles.caption} style={styleToStringUtil(captionStyle)}>
		{@render children?.()}
	</figcaption>
</figure>

// packages/react/src/lib/components/gallery/GalleryImage.tsx
import type {
	GalleryItemType,
	HTMLAttrAnchor,
	ImageType
} from "@fefade-ui/core/types"
import { classMapUtil, handleClickUtil } from "@fefade-ui/core/utils"
import {
	CSSProperties,
	forwardRef,
	ImgHTMLAttributes,
	MouseEvent,
	ReactNode,
	useState
} from "react"
import { createPortal } from "react-dom"
import Modal from "../modal"
import { Image } from "../image"
import styles from "@fefade-ui/core/styles/GalleryItem.module.css"

type HTMLImageAttr = Omit<ImgHTMLAttributes<HTMLImageElement>, "src">

interface Props
	extends HTMLImageAttr,
		GalleryItemType<CSSProperties, HTMLImageAttr>,
		HTMLAttrAnchor,
		ImageType {}

export default forwardRef<HTMLImageElement, Props>(
	(
		{
			className = "",
			lazy = false,
			dataSrc,
			href,
			target = "_self",
			download,
			viewer,
			captionStyle,
			children,
			...rest
		},
		ref
	) => {
		const [isOpen, setIsOpen] = useState(false)
		const [selectedEl, setSelectedEl] = useState<ReactNode>(null)

		function handleOpen() {
			setIsOpen(true)
		}

		function handleClose() {
			setIsOpen(false)
			setSelectedEl(null)
		}

		function handleClick(e: any) {
			handleClickUtil({
				href,
				download,
				target,
				onClick: () => {
					rest.onClick?.(e)
				}
			})
		}

		function handleImageClick(e: MouseEvent<HTMLImageElement>) {
			if (viewer) {
				const el = e.currentTarget

				const clonedImage = (
					<img
						{...(rest as HTMLImageAttr)}
						src={el.dataset.dataSrc ?? el.src}
						height={viewer.height}
						width={viewer.width}
					/>
				)

				setSelectedEl(clonedImage)
				handleOpen()
			}

			handleClick(e)
		}

		return (
			<>
				{viewer &&
					isOpen &&
					selectedEl &&
					createPortal(
						<Modal
							isOpen={isOpen}
							style={{ border: "none" }}
							handleClose={handleClose}
						>
							<Modal.Content
								style={{
									textAlign: "center",
									overflow: "hidden",
									padding: 0
								}}
							>
								{selectedEl}
							</Modal.Content>
						</Modal>,
						document.body
					)}

				<figure
					className={classMapUtil(
						className,
						[className, styles],
						styles.galleryItem,
						{
							["clickable"]: rest.onClick || viewer || href
						}
					)}
				>
					<Image
						{...rest}
						ref={ref}
						className={styles.thumbnail}
						lazy={lazy}
						dataSrc={dataSrc}
						onClick={handleImageClick}
					/>
					<figcaption className={styles.caption} style={captionStyle}>
						{children}
					</figcaption>
				</figure>
			</>
		)
	}
)
