// packages/react/src/lib/components/color-picker/ColorPicker.tsx
import { classMapUtil } from "@fefade-ui/core/utils"
import { forwardRef, InputHTMLAttributes } from "react"
import styles from "@fefade-ui/core/styles/ColorPicker.module.css"

interface Props extends Omit<InputHTMLAttributes<HTMLInputElement>, "type"> {}

export default forwardRef<HTMLInputElement, Props>(
	({ className = "", ...rest }, ref) => {
		return (
			<input
				{...rest}
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					styles.colorPicker
				)}
				type="color"
			/>
		)
	}
)

// packages/svelte/src/lib/components/color-picker/ColorPicker.svelte
<script lang="ts">
	import { classMapUtil } from "@fefade-ui/core/utils"
	import type { HTMLInputAttributes } from "svelte/elements"
	import styles from "@fefade-ui/core/styles/ColorPicker.module.css"

	interface Props extends Omit<HTMLInputAttributes, "type"> {}

	let { class: className = "", ...rest }: Props = $props()
</script>

<input
	{...rest}
	class={classMapUtil(className, [className, styles], styles.colorPicker)}
	defaultValue="#ffffff"
	type="color"
/>
