// packages/react/src/lib/components/window/Window.tsx
import { forwardRef, HTMLAttributes, ReactNode } from "react"
import { CardType, HTMLAttrAnchor } from "@fefade-ui/core/types"
import { Card } from "../card"
import { Badge } from "../badge"
import styles from "@fefade-ui/core/styles/Window.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
		CardType,
		HTMLAttrAnchor {
	label?: string | ReactNode
}

export default forwardRef<HTMLDivElement, Props>(
	({ className = "", label, children, ...rest }, ref) => {
		return (
			<Card {...rest} ref={ref} className={className}>
				<div className={styles.header}>
					<div className={styles.actions}>
						<Badge className="bg-error" roundedFull size="xs"></Badge>
						<Badge className="bg-warning" roundedFull size="xs"></Badge>
						<Badge className="bg-success" roundedFull size="xs"></Badge>
					</div>
					{label}
				</div>
				{children}
			</Card>
		)
	}
)

// packages/svelte/src/lib/components/window/Window.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import Card from "../card/index.js"
	import Badge from "../badge/index.js"
	import type { Snippet } from "svelte"
	import type { CardType, HTMLAttrAnchor } from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/Window.module.css"

	interface Props
		extends HTMLAttributes<HTMLDivElement>,
			CardType,
			HTMLAttrAnchor {
		label?: string | Snippet<[]>
	}

	let { class: className = "", label, children, ...rest }: Props = $props()
</script>

<Card {...rest} class={className}>
	<div class={styles.header}>
		<div class={styles.actions}>
			<Badge class="bg-error" roundedFull size="xs"></Badge>
			<Badge class="bg-warning" roundedFull size="xs"></Badge>
			<Badge class="bg-success" roundedFull size="xs"></Badge>
		</div>
		{#if typeof label === "string"}
			{label}
		{:else}
			{@render label?.()}
		{/if}
	</div>
	{@render children?.()}
</Card>
