// packages/svelte/src/lib/components/status/Status.svelte
<script lang="ts">
	import { Constants } from "@fefade-ui/core"
	import {
		classMapUtil,
		mergeStyleUtil,
		normalizeSizeUtil
	} from "@fefade-ui/core/utils"
	import type { HTMLAttributes } from "svelte/elements"
	import type { StatusType } from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/Status.module.css"

	interface Props
		extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
			StatusType {}

	let {
		class: className = "",
		variant = "none",
		color = Constants.themeColorVar.bg,
		size = 30,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(
		className,
		[className, styles],
		[variant, styles],
		styles.status
	)}
	style={mergeStyleUtil(
		`--color: ${color};`,
		"--bg: whitesmoke;",
		`--size: ${normalizeSizeUtil(size)};`,
		"--bounce-distance: 15%;",
		rest.style
	)}
></div>

// packages/react/src/lib/components/status/Status.tsx
import { Constants } from "@fefade-ui/core"
import { CSSProperties, forwardRef, HTMLAttributes } from "react"
import type { StatusType } from "@fefade-ui/core/types"
import { classMapUtil, normalizeSizeUtil } from "@fefade-ui/core/utils"
import styles from "@fefade-ui/core/styles/Status.module.css"

interface Props extends HTMLAttributes<HTMLDivElement>, StatusType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			variant = "none",
			color = Constants.themeColorVar.bg,
			size = 30,
			...rest
		},
		ref
	) => {
		return (
			<div
				{...rest}
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					[variant, styles],
					styles.status
				)}
				style={
					{
						["--color"]: color,
						["--bg"]: "whitesmoke",
						["--size"]: normalizeSizeUtil(size),
						["--bounce-distance"]: "15%",
						...rest.style
					} as CSSProperties
				}
			></div>
		)
	}
)
