// packages/react/src/lib/components/button/Button.tsx
import { forwardRef, type ButtonHTMLAttributes } from "react"
import type { ButtonType, HTMLAttrAnchor } from "@fefade-ui/core/types"
import styles from "@fefade-ui/core/styles/Button.module.css"
import { classMapUtil } from "@fefade-ui/core/utils"
import { Spinner } from "../spinner"

interface Props
	extends ButtonHTMLAttributes<HTMLButtonElement>, ButtonType, HTMLAttrAnchor {}

export default forwardRef<HTMLButtonElement, Props>((props, ref) => {
	const {
		className = "",
		pressedEffect = true,
		variant = "contained",
		isLoading = false,
		roundedFull = false,
		size = "sm",
		href,
		target = "_self",
		download,
		children,
		...rest
	} = props

	function handleClick(event: React.MouseEvent<HTMLButtonElement, MouseEvent>) {
		if (download && href) {
			const a = document.createElement("a")
			a.href = href
			a.download = download
			document.body.appendChild(a)
			a.click()
			document.body.removeChild(a)
		} else if (href) {
			window.open(href, target)
		} else if (typeof rest?.onClick === "function") {
			rest.onClick(event)
		}
	}

	return (
		<button
			{...rest}
			ref={ref}
			className={classMapUtil(
				className,
				[className, styles],
				[variant, styles],
				[size, styles],
				styles.button,
				{
					["roundedFull"]: roundedFull,
					[styles.pressedEffect]: pressedEffect
				}
			)}
			type={rest.type ?? "button"}
			onClick={handleClick}
		>
			{isLoading ? <Spinner /> : children}
		</button>
	)
})

// packages/svelte/src/lib/components/button/Button.svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from "svelte/elements"
	import { classMapUtil, handleClickUtil } from "@fefade-ui/core/utils"
	import type { ButtonType, HTMLAttrAnchor } from "@fefade-ui/core/types"
	import Spinner from "../spinner/index.js"
	import styles from "@fefade-ui/core/styles/Button.module.css"

	interface Props extends HTMLButtonAttributes, ButtonType, HTMLAttrAnchor {}

	let {
		class: className = "",
		pressedEffect = true,
		variant = "contained",
		isLoading = false,
		roundedFull = false,
		size = "sm",
		href,
		target = "_self",
		download,
		children,
		...rest
	}: Props = $props()
</script>

<button
	{...rest}
	class={classMapUtil(
		className,
		[className, styles],
		[variant, styles],
		[size, styles],
		styles.button,
		{
			["roundedFull"]: roundedFull,
			[styles.pressedEffect]: pressedEffect
		}
	)}
	type={rest.type ?? "button"}
	onclick={(e) => {
		handleClickUtil({
			href,
			download,
			target,
			onClick: () => {
				rest.onclick?.(e)
			}
		})
	}}
>
	{#if isLoading}
		<Spinner />
	{:else}
		{@render children?.()}
	{/if}
</button>
