// packages/vue/src/lib/components/button/Button.vue
<script setup lang="ts">
	import { computed, useAttrs, IntrinsicElementAttributes } from "vue"
	import { classMapUtil, handleClickUtil } from "@fefade-ui/core/utils"
	import type { ButtonType, HTMLAttrAnchor } from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/Button.module.css"
	import { Spinner } from "../spinner"

	interface Props extends ButtonType, HTMLAttrAnchor {}

	const {
		pressedEffect = true,
		variant = "contained",
		isLoading = false,
		roundedFull = false,
		size = "sm",
		href,
		target = "_self",
		download
	} = defineProps<Props>()

	const attrs = useAttrs() as IntrinsicElementAttributes["button"]

	const computedClass = computed(() => {
		return classMapUtil(
			attrs.class,
			[attrs.class, styles],
			[variant, styles],
			[size, styles],
			styles.button,
			{
				["roundedFull"]: roundedFull,
				[styles.pressedEffect]: pressedEffect
			}
		)
	})

	const emit = defineEmits(["click"])

	function handleClick(e: any) {
		handleClickUtil({
			href,
			download,
			target,
			onClick: () => {
				emit("click", e)
			}
		})
	}
</script>

<template>
	<button
		v-bind="attrs"
		:class="computedClass"
		:type="attrs.type ?? 'button'"
		@click="handleClick"
	>
		<Spinner v-if="isLoading" :size="size" />
		<slot />
	</button>
</template>

// packages/svelte/src/lib/components/button/Button.svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from "svelte/elements"
	import { classMapUtil, handleClickUtil } from "@fefade-ui/core/utils"
	import type { ButtonType, HTMLAttrAnchor } from "@fefade-ui/core/types"
	import Spinner from "../spinner/index.js"
	import styles from "@fefade-ui/core/styles/Button.module.css"

	interface Props extends HTMLButtonAttributes, ButtonType, HTMLAttrAnchor {}

	let {
		class: className = "",
		pressedEffect = true,
		variant = "contained",
		isLoading = false,
		roundedFull = false,
		size = "sm",
		href,
		target = "_self",
		download,
		children,
		...rest
	}: Props = $props()
</script>

<button
	{...rest}
	class={classMapUtil(
		className,
		[className, styles],
		[variant, styles],
		[size, styles],
		styles.button,
		{
			["roundedFull"]: roundedFull,
			[styles.pressedEffect]: pressedEffect
		}
	)}
	type={rest.type ?? "button"}
	onclick={(e) => {
		handleClickUtil({
			href,
			download,
			target,
			onClick: () => {
				rest.onclick?.(e)
			}
		})
	}}
>
	{#if isLoading}
		<Spinner />
	{:else}
		{@render children?.()}
	{/if}
</button>
