// packages/svelte/src/lib/components/tooltip/Tooltip.svelte
<script lang="ts">
	import { classMapUtil } from "@fefade-ui/core/utils"
	import type { TooltipType } from "@fefade-ui/core/types"
	import type { HTMLAttributes } from "svelte/elements"
	import styles from "@fefade-ui/core/styles/Tooltip.module.css"

	interface Props
		extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
			TooltipType {}

	let {
		class: className = "",
		label,
		position = "top",
		children,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	data-tooltip={label}
	class={classMapUtil(
		className,
		[className, styles],
		[position, styles],
		styles.tooltip
	)}
>
	{@render children?.()}
</div>

// packages/react/src/lib/components/tooltip/Tooltip.tsx
import { forwardRef, HTMLAttributes } from "react"
import { classMapUtil } from "@fefade-ui/core/utils"
import type { TooltipType } from "@fefade-ui/core/types"
import styles from "@fefade-ui/core/styles/Tooltip.module.css"

interface Props
	extends Omit<HTMLAttributes<HTMLDivElement>, "color">,
		TooltipType {}

export default forwardRef<HTMLDivElement, Props>(
	({ className = "", label, position = "top", children, ...rest }, ref) => {
		return (
			<div
				{...rest}
				ref={ref}
				data-tooltip={label}
				className={classMapUtil(
					className,
					[className, styles],
					[position, styles],
					styles.tooltip
				)}
			>
				{children}
			</div>
		)
	}
)
