// packages/vue/src/lib/components/grid/Grid.vue
<script setup lang="ts">
	import {
		computed,
		CSSProperties,
		IntrinsicElementAttributes,
		useAttrs
	} from "vue"
	import { classMapUtil, normalizeSizeUtil } from "@fefade-ui/core/utils"
	import type { GridType } from "@fefade-ui/core/types"
	import styles from "@fefade-ui/core/styles/Grid.module.css"

	interface Props extends GridType {}

	const {
		variant,
		columns = "auto-fit",
		gap = "0.75rem",
		minWidth = "12.5rem",
		maxWidth = "1fr"
	} = defineProps<Props>()

	const attrs = useAttrs() as IntrinsicElementAttributes["div"]

	const computedClass = computed(() =>
		classMapUtil(
			attrs.class,
			[attrs.class, styles],
			[variant, styles],
			styles.grid
		)
	)

	const gridStyle = computed(() => ({
		"--columns": columns,
		"--gap": normalizeSizeUtil(gap),
		"--min-width": normalizeSizeUtil(minWidth),
		"--max-width": normalizeSizeUtil(maxWidth),
		...(attrs.style as CSSProperties)
	}))
</script>

<template>
	<div v-bind="attrs" :class="computedClass" :style="gridStyle">
		<slot />
	</div>
</template>

// packages/react/src/lib/components/grid/Grid.tsx
import { CSSProperties, forwardRef, HTMLAttributes } from "react"
import { classMapUtil, normalizeSizeUtil } from "@fefade-ui/core/utils"
import type { GridType } from "@fefade-ui/core/types"
import styles from "@fefade-ui/core/styles/Grid.module.css"

interface Props extends HTMLAttributes<HTMLDivElement>, GridType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			variant,
			columns = "auto-fit",
			gap = "0.75rem",
			minWidth = "12.5rem",
			maxWidth = "1fr",
			children,
			...rest
		},
		ref
	) => {
		return (
			<div
				{...rest}
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					[variant, styles],
					styles.grid
				)}
				style={
					{
						["--columns"]: columns,
						["--gap"]: normalizeSizeUtil(gap),
						["--min-width"]: normalizeSizeUtil(minWidth),
						["--max-width"]: normalizeSizeUtil(maxWidth),
						...rest.style
					} as CSSProperties
				}
			>
				{children}
			</div>
		)
	}
)
