// packages/react/src/lib/components/drawer/DrawerHeader.tsx
import { forwardRef, HTMLAttributes } from "react"
import { classMapUtil } from "@fefade-ui/core/utils"
import { closeIcon } from "@fefade-ui/core/icons"
import { Button } from "../button"
import styles from "@fefade-ui/core/styles/DrawerHeader.module.css"

export interface Props extends HTMLAttributes<HTMLDivElement> {
	handleClose?: () => void
}

export default forwardRef<HTMLDivElement, Props>((props, ref) => {
	const { className = "", handleClose, children, ...rest } = props

	return (
		<div
			{...rest}
			ref={ref}
			className={classMapUtil(
				className,
				[className, styles],
				styles.drawerHeader,
				{
					[styles.isClosable]: Boolean(handleClose)
				}
			)}
		>
			{children}
			{handleClose && (
				<Button
					variant="text"
					className={styles.buttonClose}
					onClick={handleClose}
				>
					<svg
						viewBox="0 -960 960 960"
						style={{
							display: "inline-block",
							verticalAlign: "middle",
							fill: "currentcolor",
							width: "24px",
							height: "24px"
						}}
					>
						<path d={closeIcon}></path>
					</svg>
				</Button>
			)}
		</div>
	)
})

// packages/svelte/src/lib/components/drawer/DrawerHeader.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import Button from "../button/index.js"
	import { closeIcon } from "@fefade-ui/core/icons"
	import styles from "@fefade-ui/core/styles/DrawerHeader.module.css"

	interface Props extends HTMLAttributes<HTMLDivElement> {
		handleClose?: () => void
	}

	let {
		class: className = "",
		handleClose,
		children,
		...rest
	}: Props = $props()
</script>

<div
	{...rest}
	class={classMapUtil(className, [className, styles], styles.drawerHeader, {
		[styles.isClosable]: Boolean(handleClose)
	})}
>
	{@render children?.()}
	{#if handleClose}
		<Button variant="text" class={styles.buttonClose} onclick={handleClose}>
			<svg
				viewBox="0 -960 960 960"
				style="
				display: inline-block; 
				vertical-align: middle;
				fill: currentColor;
				width: 24px;
				height: 24px;
				"
			>
				<path d={closeIcon}></path>
			</svg>
		</Button>
	{/if}
</div>
