// packages/vue/src/lib/components/badge/Badge.vue
<script setup lang="ts">
	import { useAttrs, computed, IntrinsicElementAttributes } from "vue"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import styles from "@fefade-ui/core/styles/Badge.module.css"
	import type { BadgeType } from "@fefade-ui/core/types"

	interface Props extends BadgeType {}

	const {
		size = "xs",
		variant = "contained",
		roundedFull = false
	} = defineProps<Props>()

	const attrs = useAttrs() as IntrinsicElementAttributes["div"]

	const computedClass = computed(() =>
		classMapUtil(
			attrs.class,
			[attrs.class, styles],
			styles.badge,
			[size, styles],
			[variant, styles],
			{
				[styles.roundedFull]: roundedFull
			}
		)
	)
</script>

<template>
	<span v-bind="attrs" :class="computedClass">
		<slot />
	</span>
</template>

// packages/react/src/lib/components/badge/Badge.tsx
import { forwardRef, HTMLAttributes } from "react"
import { classMapUtil } from "@fefade-ui/core/utils"
import styles from "@fefade-ui/core/styles/Badge.module.css"
import type { BadgeType } from "@fefade-ui/core/types"

interface Props extends HTMLAttributes<HTMLSpanElement>, BadgeType {}

export default forwardRef<HTMLDivElement, Props>(
	(
		{
			className = "",
			size = "xs",
			variant = "contained",
			roundedFull = false,
			children,
			...rest
		},
		ref
	) => {
		return (
			<span
				{...rest}
				ref={ref}
				className={classMapUtil(
					className,
					[className, styles],
					styles.badge,
					[size, styles],
					[variant, styles],
					{
						[styles.roundedFull]: roundedFull
					}
				)}
			>
				{children}
			</span>
		)
	}
)
