// packages/react/src/lib/components/overlay/Overlay.tsx
import { ButtonHTMLAttributes, forwardRef } from "react"
import { classMapUtil } from "@fefade-ui/core/utils"
import styles from "@fefade-ui/core/styles/Overlay.module.css"

export interface Props extends ButtonHTMLAttributes<HTMLButtonElement> {
	isOpen: boolean
}

export default forwardRef<HTMLButtonElement, Props>((props, ref) => {
	const { className = "", isOpen = false, ...rest } = props

	if (!isOpen) return null

	return (
		<button
			{...rest}
			ref={ref}
			className={classMapUtil(className, [className, styles], styles.overlay)}
			type={"button"}
			aria-labelledby="overlay"
			aria-label="Close overlay"
		/>
	)
})

// packages/svelte/src/lib/components/overlay/Overlay.svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from "svelte/elements"
	import { classMapUtil } from "@fefade-ui/core/utils"
	import styles from "@fefade-ui/core/styles/Overlay.module.css"

	interface Props extends HTMLButtonAttributes {
		isOpen: boolean
	}

	let { class: className = "", isOpen = false, ...rest }: Props = $props()
</script>

{#if isOpen}
	<button
		{...rest}
		class={classMapUtil(className, [className, styles], styles.overlay)}
		type="button"
		aria-labelledby="overlay"
		aria-label="Close overlay"
		onclick={(e) => {
			document.body.style.overflowY = "auto"
			rest.onclick?.(e)
		}}
	>
	</button>
{/if}
